services:
  db:
    container_name: gin-todo
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword123
      MYSQL_DATABASE: posdb
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -pyourpassword123"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  db:
    driver: bridge

volumes:
  db:
